### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by rinkeb** [hogjosh/TSMessages.monotouch#1]
Hi there,

I was wondering if your bindings are still useable? I followed your make instructions, but i get some compile errors..

My setup:
Mac OS X 10.8.5
XCode 5.0.2

Regards

**Comment by hogjosh** [comment]
Hm, what errors are you getting?  Did you clone the repository recursively?  I just cloned it again and it built successfully.  Granted I'm on 10.9 and running the latest alpha of Xamarin.iOS 7.0...

**Comment by rinkeb** [comment]
Thanx for your response. 
Seems i did not have a full recursive clone after all. Guess i need to do my git homework better :-)

For any one else coping with github procedures, here is what i did to make it work:
- Install git on the mac using https://code.google.com/p/git-osx-installer/

In a terminal window: 
- git clone https://github.com/JHogan13/TSMessages.monotouch --recursive
- cd TSMessages.Monotouch/
- git submodule foreach --recursive git checkout master
- make

If the build succeeds, the dll to use in Monotouch is in the current directory.
